## Comments 
### Reviewer 1.
-  2. I recommend clarifying the predictors that have been included for the models.
    - Todo : 어떤 변수들을 삭제했고 넣었었는지

- 3. I am curious if those models were trained using the default configuration of the package or were fine-tuned?
    - Todo : Search space 명시해줄 것

- 4. Regarding the model that was trained using synthetic data  outperforming those trained with original data, can the authors please  clarify a bit more what was the validating/testing set for the model  trained using original data? I might have missed it but  if the model was trained and tested/validated using the same set of  data, it usually comes with a high AUC or accuracy. It can be very  challenging for let a model that was trained using a completely external  data (synthetic) data and validated on a different  data (original real data) to beat its performance.
    - Todo : Test set을 어떻게 해줬는지, 어떻게 떼어서 했는지 써줄 것 validation set 비율 써줄 것, 


### Reviewer 2.
- 1. What was the rationale for the ML models that were chosen i.e., decision trees instead of neural networks?
    - Todo : 기본 Neural Network 실험을 다시, 결과를 김현욱 선생님께 공유드릴 것.

- 3. The MMR-deficiency rate was much higher in the synthetic data. In a  clinical setting, this would indicate a 30% increase in incidence of the  molecular change being detected in the population. The models performed  better on synthetic database despite an altered  molecular marker. Was any analysis carried out where the information  from 4 MMR genes (MLH1, MSH2, MSH6, and PALB2) were treated as a single  feature?
    - Todo : Feature importance를 한번 확인해보고 어떻게 됐는지 보자.

2. I recommend clarifying the predictors that have been included for the models.
    - Todo : 어떤 변수들을 삭제했고 넣었었는지

In [17]:
from pathlib import Path
import os
projectPath = Path().cwd().parent
print(projectPath)
dataPath = projectPath.joinpath('data/processed/2_produce_data/synthetic_decoded')
oriPath = projectPath.joinpath('data/processed/1_preprocess/unmodified_D0_50.pkl')

import pandas as pd
import pickle

/home/wonseok/projects/2022_DATA_SYNTHESIS/young_age

In [18]:
syn_df = pd.read_csv(dataPath.joinpath('Synthetic_data_epsilon10000_50.csv'))
syn_df.drop(columns = 'Unnamed: 0', inplace=True)

# load original data
ori_df = pd.read_pickle(oriPath)
ori_df.head()

,PT_SBST_NO,BSPT_SEX_CD,BSPT_IDGN_AGE,BSPT_FRST_DIAG_NM,BSPT_STAG_CLSF_CD,BSPT_STAG_VL,RLPS,RLPS DIFF,DEAD,DEAD_DIFF,...,REGN_CASB_CSTR_PRPS_NM_7,REGN_TIME_DIFF_7,REGN_START_DIFF_7,REGN_CSTR_CYCL_VL_END_7,REGN_CSTR_REGN_NM_8,REGN_CSTR_PRPS_NT_8,REGN_CASB_CSTR_PRPS_NM_8,REGN_TIME_DIFF_8,REGN_START_DIFF_8,REGN_CSTR_CYCL_VL_END_8
1,92,0,7,0,1,3.0,1,15.0,1,28.0,...,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN
3,262,1,10,0,1,1.0,0,NaN,0,NaN,...,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN
4,1041,1,8,0,1,3.0,0,NaN,0,NaN,...,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN
5,275,0,9,0,1,3.0,0,NaN,0,NaN,...,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN
7,1019,1,8,2,1,3.0,0,NaN,0,NaN,...,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN

In [8]:
syn_df.head(10)

,PT_SBST_NO,BSPT_SEX_CD,BSPT_IDGN_AGE,BSPT_FRST_DIAG_NM,BSPT_STAG_CLSF_CD,BSPT_STAG_VL,RLPS,RLPS_DIFF,DEAD,DEAD_DIFF,...,REGN_CASB_CSTR_PRPS_NM_7,REGN_TIME_DIFF_7,REGN_START_DIFF_7,REGN_CSTR_CYCL_VL_END_7,REGN_CSTR_REGN_NM_8,REGN_CSTR_PRPS_NT_8,REGN_CASB_CSTR_PRPS_NM_8,REGN_TIME_DIFF_8,REGN_START_DIFF_8,REGN_CSTR_CYCL_VL_END_8
0,ukkdwfjirt0,1,46,2,2,1,1,1122.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
1,ikbofyqdhb1,0,46,0,2,1,1,370.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
2,xiaxfpzzgy2,1,49,2,2,1,1,830.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
3,xpfjrqqlof3,0,45,1,2,1,1,720.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
4,wtpwnllbhx4,1,45,2,2,1,1,1109.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
5,qhpwaesxvc5,0,47,1,2,1,1,735.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
6,ikfggebvef6,1,43,2,2,1,1,1122.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
7,fgdyrpusjx7,1,38,2,2,1,1,407.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
8,eryctdnlne8,1,49,2,2,1,1,830.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN
9,rgpcvukzrf9,0,47,0,2,1,1,371.0,0,NaN,...,1,0,0,NaN,1,NaN,1,0,0,NaN